name: Tagging

on:
  push:
    branches: [ "main" ]
    
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generating tag
        run: echo "::set-output name=tag::$(date + '%Y%m%d')${GITHUB_REF##*/}"
      - name: Displaying tag
        run: |
          echo ${{ steps.date.outputs.tag }}
          echo ${GITHUB_REF##*/}
      - name: Push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.date.outputs.tag }}
