name: Tagging

on:
  push:
    branches: [ "main" ]
    
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$('%Y%m%d')"
      - name: Displaying tag
        run: |
          echo ${{ steps.date.outputs.date }}
          echo ${GITHUB_REF##*/}
      - name: Push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.date.outputs.date }}-${GITHUB_REF##*/}
