name: Tagging

on:
  push:
    branches: [ "main" ]
    
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generating tag
        run: echo "tag=${GITHUB_REF##*/}-$(date +'%m.%d.%Y-%M.%S')" >> $GITHUB_ENV
      - name: Push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.tag }}
